name: easy_market
description: The project consists in creating, editing, and sharing grocery lists by users in real time.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  android_intent_plus: ^3.1.1
  bloc: ^8.0.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_search: ^5.0.2
  dynamic_color: ^1.4.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_dynamic_links: ^4.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.3
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  lexicographical_order: ^1.3.5
  modular_bloc_bind: ^1.0.1
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.1.10
  fake_cloud_firestore: ^1.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.8.4
  mockito: ^5.1.0
  modular_codegen: ^3.0.4

flutter:
  assets:
    - assets/images/
  generate: true
  uses-material-design: true