// Mocks generated by Mockito 5.1.0 from annotations
// in market_lists/test/app/modules/grocery/mock_groceries_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:market_lists/app/modules/grocery/domain/errors/errors.dart'
    as _i6;
import 'package:market_lists/app/modules/grocery/grocery.dart' as _i7;
import 'package:market_lists/app/modules/grocery/infra/models/grocery_list_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'mock_groceries_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeGroceryListModel_1 extends _i1.Fake implements _i3.GroceryListModel {
}

/// A class which mocks [GroceryRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceryRepositoryTest extends _i1.Mock
    implements _i4.GroceryRepositoryTest {
  MockGroceryRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.GroceryList>> createGroceryList(
          _i7.GroceryList? groceryList) =>
      (super.noSuchMethod(Invocation.method(#createGroceryList, [groceryList]),
          returnValue: Future<_i2.Either<_i6.Failure, _i7.GroceryList>>.value(
              _FakeEither_0<_i6.Failure, _i7.GroceryList>())) as _i5
          .Future<_i2.Either<_i6.Failure, _i7.GroceryList>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>> updateGroceryList(
          _i7.GroceryList? groceryList) =>
      (super.noSuchMethod(Invocation.method(#updateGroceryList, [groceryList]),
              returnValue: Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Unit>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>> deleteGroceryList(
          _i7.GroceryList? groceryList) =>
      (super.noSuchMethod(Invocation.method(#deleteGroceryList, [groceryList]),
              returnValue: Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Unit>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
}

/// A class which mocks [GroceryDatasourceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceryDatasourceTest extends _i1.Mock
    implements _i4.GroceryDatasourceTest {
  MockGroceryDatasourceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.GroceryListModel> createGroceryList(
          _i3.GroceryListModel? groceryList) =>
      (super.noSuchMethod(Invocation.method(#createGroceryList, [groceryList]),
              returnValue:
                  Future<_i3.GroceryListModel>.value(_FakeGroceryListModel_1()))
          as _i5.Future<_i3.GroceryListModel>);
  @override
  _i5.Future<void> updateGroceryList(_i3.GroceryListModel? groceryList) =>
      (super.noSuchMethod(Invocation.method(#updateGroceryList, [groceryList]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteGroceryList(String? id) =>
      (super.noSuchMethod(Invocation.method(#deleteGroceryList, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}
